services:
  energygrid-backend:
    image: ${ECR_REGISTRY}/energygrid-backend:latest

  energygrid-frontend:
    image: ${ECR_REGISTRY}/energygrid-frontend:latest

  energygrid-simulator:
    image: ${ECR_REGISTRY}/energygrid-simulator:latest

  energygrid-nginx:
    image: ${ECR_REGISTRY}/energygrid-nginx:latest

  munin-master:
    image: ${ECR_REGISTRY}/energygrid-munin-master:latest
